# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
    - master
    tags:
    - v\d+\.\d+\.\d+

env:
  PROJECT_ID: storymadesimple

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Set ENV
      run: |- 
        if [ ${GITHUB_REF##*/} = "master" ]; then 
          echo "::set-env name=ENV::staging"
        else 
          echo "::set-env name=ENV::prod"
        fi
    - name: Set ENV
      run: |-
        if [ ${GITHUB_REF##*/} = "master" ]; then
          echo "ENV=staging" >> $GITHUB_ENV
        else 
          echo "ENV=prod" >> $GITHUB_ENV
        fi

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Build the Docker image
    - name: Build
      run: |-
        make build
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        make push 
    - name: Deploy
      run: |-
        make deploy